package com.italiano2774.nativeapp;

import android.app.AlertDialog;import android.app.DatePickerDialog;import android.app.TimePickerDialog;import android.os.Bundle;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.fragment.app.Fragment;import com.google.android.material.switchmaterial.SwitchMaterial;import java.time.LocalDate;import java.util.Arrays;

public class SettingsFragment extends Fragment {
    private ProgressStore progress;private WordRepository repo;private Button dateButton,timeButton;private Spinner perDay,sessionMinutes,pronMode,retention;private SwitchMaterial original,reminder;private LocalDate selectedDate;private int reminderHour,reminderMinute;
    @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){
        View v=i.inflate(R.layout.fragment_settings,c,false);progress=new ProgressStore(requireContext());repo=WordRepository.get(requireContext());selectedDate=progress.startDate();reminderHour=progress.reminderHour();reminderMinute=progress.reminderMinute();
        dateButton=v.findViewById(R.id.button_start_date);timeButton=v.findViewById(R.id.button_reminder_time);perDay=v.findViewById(R.id.spinner_per_day);sessionMinutes=v.findViewById(R.id.spinner_session_minutes);pronMode=v.findViewById(R.id.spinner_pronunciation_mode);retention=v.findViewById(R.id.spinner_retention);original=v.findViewById(R.id.switch_original_audio);reminder=v.findViewById(R.id.switch_reminder);dateButton.setText(selectedDate.toString());updateReminderText();dateButton.setOnClickListener(x->pickDate());timeButton.setOnClickListener(x->pickTime());
        Integer[] opts={20,25,30,40,50,100};ArrayAdapter<Integer>a=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,opts);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);perDay.setAdapter(a);int idx=Arrays.asList(opts).indexOf(progress.perDay());perDay.setSelection(idx<0?2:idx);
        Integer[] mins={5,15,30,60};ArrayAdapter<Integer>ma=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,mins);ma.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);sessionMinutes.setAdapter(ma);int mi=Arrays.asList(mins).indexOf(progress.sessionMinutes());sessionMinutes.setSelection(mi<0?2:mi);
        String[] ret={"85% · 更少复习","90% · 推荐","95% · 更牢固"};ArrayAdapter<String>ra=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,ret);ra.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);retention.setAdapter(ra);double rv=progress.desiredRetention();retention.setSelection(rv>=0.94?2:(rv<0.88?0:1));
        String[] pron={"总是显示","自动隐藏（推荐）","点击/显示答案后显示","永不显示"};ArrayAdapter<String>pa=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,pron);pa.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);pronMode.setAdapter(pa);pronMode.setSelection(progress.pronunciationMode());
        original.setChecked(progress.preferOriginalAudio());reminder.setChecked(progress.reminderEnabled());v.findViewById(R.id.button_placement_settings).setOnClickListener(x->((MainActivity)requireActivity()).openPlacementTest());
        v.findViewById(R.id.button_save_settings).setOnClickListener(x->{progress.setStartDate(selectedDate);progress.setPerDay((Integer)perDay.getSelectedItem());progress.setSessionMinutes((Integer)sessionMinutes.getSelectedItem());progress.setDesiredRetention(retention.getSelectedItemPosition()==0?0.85:(retention.getSelectedItemPosition()==2?0.95:0.90));progress.setPronunciationMode(pronMode.getSelectedItemPosition());progress.setPreferOriginalAudio(original.isChecked());progress.setReminderEnabled(reminder.isChecked());progress.setReminderTime(reminderHour,reminderMinute);if(reminder.isChecked()){((MainActivity)requireActivity()).requestNotificationPermissionIfNeeded();ReminderScheduler.schedule(requireContext(),reminderHour,reminderMinute);}else ReminderScheduler.cancel(requireContext());Toast.makeText(requireContext(),"设置已保存",Toast.LENGTH_SHORT).show();refreshStats(v);});
        v.findViewById(R.id.button_export).setOnClickListener(x->((MainActivity)requireActivity()).exportProgress());v.findViewById(R.id.button_import).setOnClickListener(x->((MainActivity)requireActivity()).importProgress());v.findViewById(R.id.button_reset).setOnClickListener(x->new AlertDialog.Builder(requireContext()).setTitle("清空学习进度？").setMessage("掌握度、四维进度、FSRS记忆状态、错词本、易混记录、阶段自测成绩、详细学习事件和收藏会清空；学习计划、提醒与目标记忆保持率设置保留。").setNegativeButton("取消",null).setPositiveButton("清空",(d,w)->{progress.reset();refreshStats(v);Toast.makeText(requireContext(),"已清空",Toast.LENGTH_SHORT).show();}).show());refreshStats(v);return v;
    }
    private void pickDate(){DatePickerDialog d=new DatePickerDialog(requireContext(),(view,y,m,day)->{selectedDate=LocalDate.of(y,m+1,day);dateButton.setText(selectedDate.toString());},selectedDate.getYear(),selectedDate.getMonthValue()-1,selectedDate.getDayOfMonth());d.show();}
    private void pickTime(){TimePickerDialog d=new TimePickerDialog(requireContext(),(view,h,m)->{reminderHour=h;reminderMinute=m;updateReminderText();},reminderHour,reminderMinute,true);d.show();}
    private void updateReminderText(){if(timeButton!=null)timeButton.setText(String.format("提醒时间  %02d:%02d",reminderHour,reminderMinute));}
    private void refreshStats(View v){TextView t=v.findViewById(R.id.text_stats),ps=v.findViewById(R.id.text_placement_status);ps.setText(progress.placementCompleted()?"上次测试保守跳过约 "+progress.placementKnownEstimate()+" 个已会词。":"尚未进行入门测试。新用户建议先测试，可减少重复学习。");t.setText("已接触："+progress.introducedCount(repo.all())+" / "+repo.size()+"\nB1可用（四维门槛）："+progress.b1Count(repo.all())+" / 1600\n完全掌握（综合5级）："+progress.strongCount(repo.all())+"\n今日待复习："+progress.dueCount(repo.all(),LocalDate.now())+" · 建议新词："+progress.recommendedNewWords(repo.all())+"\n最近7天正确率："+progress.sevenDayAccuracy()+"% · FSRS目标保持率："+(int)Math.round(progress.desiredRetention()*100)+"%\n错词本："+progress.wrongTotal(repo.all())+"\n四维平均：识义 "+progress.dimensionAverage(repo.all(),ProgressStore.DIM_MEANING)+"% · 听力 "+progress.dimensionAverage(repo.all(),ProgressStore.DIM_LISTENING)+"% · 拼写 "+progress.dimensionAverage(repo.all(),ProgressStore.DIM_SPELLING)+"% · 口语 "+progress.dimensionAverage(repo.all(),ProgressStore.DIM_SPEAKING)+"%\n阶段自测最好：A1 "+progress.bestExamScore("A1")+"% · A2 "+progress.bestExamScore("A2")+"% · B1 "+progress.bestExamScore("B1")+"%\n练习总正确率："+progress.totalAccuracy(repo.all())+"% · 连续学习："+progress.activityStreak()+" 天");}
}
