package com.italiano2774.nativeapp;

import android.os.Bundle;import android.text.*;import android.view.*;import android.widget.*;import androidx.annotation.*;import androidx.fragment.app.Fragment;import androidx.recyclerview.widget.LinearLayoutManager;import androidx.recyclerview.widget.RecyclerView;import java.util.*;

public class VocabularyFragment extends Fragment{
 private WordRepository repo;private ProgressStore progress;private AudioPlayer audio;private WordAdapter adapter;private EditText search;private Spinner topic;private CheckBox fav,low,wrong;private TextView count;
 @Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle s){View v=i.inflate(R.layout.fragment_vocabulary,c,false);repo=WordRepository.get(requireContext());progress=new ProgressStore(requireContext());audio=new AudioPlayer(requireContext(),progress);search=v.findViewById(R.id.edit_search);topic=v.findViewById(R.id.spinner_topic);fav=v.findViewById(R.id.check_favorite);low=v.findViewById(R.id.check_low);wrong=v.findViewById(R.id.check_wrong);count=v.findViewById(R.id.text_count);RecyclerView rv=v.findViewById(R.id.recycler_vocabulary);rv.setLayoutManager(new LinearLayoutManager(requireContext()));adapter=new WordAdapter(requireContext(),progress,audio,this::filter);rv.setAdapter(adapter);
  List<String> ts=new ArrayList<>();ts.add("全部主题");ts.addAll(repo.topics());ArrayAdapter<String>a=new ArrayAdapter<>(requireContext(),android.R.layout.simple_spinner_item,ts);a.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);topic.setAdapter(a);topic.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View x,int n,long id){filter();}});fav.setOnCheckedChangeListener((b,x)->filter());low.setOnCheckedChangeListener((b,x)->filter());wrong.setOnCheckedChangeListener((b,x)->filter());search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){filter();}public void afterTextChanged(Editable e){}});v.findViewById(R.id.button_open_custom_library).setOnClickListener(x->((MainActivity)requireActivity()).openCustomLibrary());filter();return v;}
 private void filter(){if(adapter==null)return;String q=search.getText().toString().trim().toLowerCase(Locale.ROOT);String t=topic.getSelectedItem()==null?"全部主题":topic.getSelectedItem().toString();List<Word> out=new ArrayList<>();for(Word w:repo.all()){if(!t.equals("全部主题")&&!w.level.equals(t))continue;if(fav.isChecked()&&!progress.favorite(w.id))continue;if(low.isChecked()&&progress.mastery(w.id)>=4)continue;if(wrong.isChecked()&&progress.wrongCount(w.id)<=0)continue;String hay=(w.word+" "+w.english+" "+w.chinese+" "+w.zhPron+" "+w.lemma+" "+w.formInfo).toLowerCase(Locale.ROOT);if(!q.isEmpty()&&!hay.contains(q))continue;out.add(w);if(out.size()>=400)break;}count.setText("显示 "+out.size()+" 项（最多显示400项，继续搜索可缩小范围）");adapter.submit(out);}
 @Override public void onDestroyView(){if(audio!=null)audio.release();super.onDestroyView();}
}
